# -*- coding: utf-8 -*-
"""Mini_Sistema_Bancario_Desafio_DIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ji3OUrHPkxOZwjSELQxpFxjf_a5E97lx
"""

menu = """

[u] Criar usuario
[c] Criar conta corrente
[d] Depositar
[s] Sacar
[e] Extrato
[q] Sair

=> """

saldo = 0
limite = 500
extrato = ""
numero_saques = 0
LIMITE_SAQUES = 3

usuarios = []
contas = []

def criar_usuario(usuarios, nome, data_nascimento, cpf, endereco):
    for usuario in usuarios:
        if usuario["cpf"] == cpf:
            print("Já existe um usuário com esse CPF.")
            return

    usuario = {
      "nome": nome,
      "data_nascimento": data_nascimento,
      "cpf": cpf,
      "endereco": endereco
    }

    usuarios.append(usuario)
    print("Usuário criado com sucesso!")

def criar_conta_corrente(usuarios, contas, cpf):
  usuario_encontrado = None

  for usuario in usuarios:
    if usuario["cpf"] == cpf:
      usuario_encontrado = usuario
      break

  # This block was incorrectly indented inside the for loop
  if not usuario_encontrado:
    print("Usuario não encontrado. Conta não criada")
    return

  numero_conta = len(contas) + 1

  conta = {
      "agencia": "0001",
      "numero_conta": numero_conta,
      "usuario": usuario_encontrado
  }

  contas.append(conta)
  print("Conta corrente criada com sucesso!")


def depositar(saldo, valor, extrato, /):
  if valor > 0:
    saldo += valor
    extrato += f"Depósito: R$ {valor:.2f}\n"
  else:
    print("Operação falhou! O valor informado é inválido.")

  return saldo, extrato

def sacar(*, saldo, valor, extrato, limite, numero_saques, limite_saques):
  excedeu_saldo = valor > saldo
  excedeu_limite = valor > limite
  excedeu_saques = numero_saques >= limite_saques

  if excedeu_saldo:
    print("Operação falhou! Você não tem saldo suficiente.")

  elif excedeu_limite:
    print("Operação falhou! O valor do saque excedeu o limite.")

  elif excedeu_saques:
    print("Operação falhou! Número máximo de saques excedido.")

  elif valor > 0:
    saldo -= valor
    extrato += f"Saque: R$ {valor:.2f}\n"
    numero_saques += 1

  else: # Added colon here
    print("Operação falhou! O valor informado é inválido.")

  return saldo, extrato, numero_saques

def exibir_extrato(saldo, /, *, extrato):
  print("\n==========================EXTRATO==========================")
  print("Não foram realizadas movimentações." if not extrato else extrato)
  print(f"\nSaldo: R$ {saldo:.2f}") # Corrected "nSaldo" to "\nSaldo"
  print("============================================================")

while True:

    opcao = input(menu)

    if opcao == "u":
      nome = input("Informe o nome do usuário: ")
      data_nascimento = input("Informe a data de nascimento do usuário (dd/mm/aaaa): ")
      cpf = input ("Informe o CPF do usuário (somente números): ")
      cpf = "".join([c for c in cpf if c.isdigit()]) # Corrected `for in cpf` to `for c in cpf`
      endereco = input("Informe o endereço do usuário: ")

      criar_usuario(usuarios, nome, data_nascimento, cpf, endereco)

    elif opcao == "c":
      cpf = input("Informe o CPF do usuário:")
      cpf = "".join([c for c in cpf if c.isdigit()])

      criar_conta_corrente(usuarios, contas, cpf)

    if opcao == "d":
        valor = float(input("Informe o valor do depósito: "))

        if valor > 0:
            saldo += valor
            extrato += f"Depósito: R$ {valor:.2f}\n"

        else:
            print("Operação falhou! O valor informado é inválido.")

    elif opcao == "s":
        valor = float(input("Informe o valor do saque: "))

        excedeu_saldo = valor > saldo

        excedeu_limite = valor > limite

        excedeu_saques = numero_saques >= LIMITE_SAQUES

        if excedeu_saldo:
            print("Operação falhou! Você não tem saldo suficiente.")

        elif excedeu_limite:
            print("Operação falhou! O valor do saque excede o limite.")

        elif excedeu_saques:
            print("Operação falhou! Número máximo de saques excedido.")

        elif valor > 0:
            saldo -= valor
            extrato += f"Saque: R$ {valor:.2f}\n"
            numero_saques += 1

        else:
            print("Operação falhou! O valor informado é inválido.")

    elif opcao == "e":
        print("\n================ EXTRATO ================")
        print("Não foram realizadas movimentações." if not extrato else extrato)
        print(f"\nSaldo: R$ {saldo:.2f}")
        print("=========================================")

    elif opcao == "q":
        break

    else:
        print("Operação inválida, por favor selecione novamente a operação desejada.")